site_name: Sensai
site_description: LLM chatbot with unlimited functionalities !
site_author: Ethan Charpentier, Tom Gatin, Eliott Raguin, Alexis Clemot
repo_name: EthanCharpentier667/SenseiUwuMirror
repo_url: https://github.com/EthanCharpentier667/SenseiUwuMirror
edit_uri: blob/main/docs/

theme:
  name: material
  language: en
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true
            show_signature_annotations: true
            separate_signature: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - API Reference: reference/
