[project]
name = "sensai"
version = "0.1.0"
description = "LLM chatbot with unlimited functionalities !"
readme = "README.md"
authors = [
    { name = "EthanCharpentier667", email = "ethan.charpentier@epitech.eu" },
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
sensai = "sensai:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
